### ISSUE TITLE
Kotlin extensions

### ISSUE THREAD

**Issue by lub0s** [SidneyXu/AndroidDemoIn4Languages#2]
Why is the kotlin code without these extensions https://kotlinlang.org/docs/tutorials/android-plugin.html ? it would reduce your code a bit and make it more readable imo

**Comment by SidneyXu** [comment]
Actually kotlin extension was already used.

``` groovy
dependencies {
    classpath 'com.android.tools.build:gradle:1.3.1'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"
}
```

The official page is outdated.

**Comment by abreslav** [comment]
Then the "Find View" section needs to be updated to something like:

Kotlin

With [Kotlin Android Extensions](https://kotlinlang.org/docs/tutorials/android-plugin.html) enabled (no extra dependencies needed):

``` kotlin
val title = view.text1
```

(maybe mention the old way too, but as a fallback)

**Comment by SidneyXu** [comment]
close #4
